#target photoshop
#include "../../../../../../operacao/lib/mkroot.jsxinc"
/* Read request from WORK/00_MATRIZ/render_request.json. Output folder must be new.
   Does not modify a template. Export from exact named layer comp only. */
(function(){var ROOT=MK.root(),BASE=ROOT+'/Projects/BYD/Jobs/V4/',REFUSE_OVERWRITE=true,doc=null,log=null,old=app.displayDialogs,start=new Date().getTime();
function msg(s){if(log){log.writeln(new Date().toUTCString()+'|'+s);log.close();log.open('a');}}
try{if(app.documents.length)throw Error('PREFLIGHT_DOCS_ABERTOS');var sf=new File(BASE+'WORK/00_MATRIZ/render_request.json');if(!sf.exists)throw Error('MISSING_RENDER_REQUEST');sf.encoding='UTF8';sf.open('r');var job=eval('('+sf.read()+')');sf.close();if(!job.output_folder||!job.log_file||!job.templates||!job.offer_ids)throw Error('INVALID_REQUEST');var folder=new Folder(BASE+job.output_folder);if(folder.exists)throw Error('REFUSE_OVERWRITE_OUTPUT_FOLDER');if(!folder.create())throw Error('CANNOT_CREATE_OUTPUT_FOLDER');log=new File(BASE+job.log_file);if(log.exists)throw Error('REFUSE_OVERWRITE_LOG');log.encoding='UTF8';log.open('w');app.displayDialogs=DialogModes.NO;
for(var f=0;f<job.templates.length;f++){var t=job.templates[f],t0=new Date().getTime();doc=app.open(new File(BASE+t.path));if(doc.mode!==DocumentMode.RGB||doc.bitsPerChannel!==BitsPerChannelType.EIGHT)throw Error('MODE_PROFILE_PREFLIGHT');if(doc.colorProfileName!=='sRGB IEC61966-2.1')throw Error('PROFILE_NOT_SRGB');for(var i=0;i<job.offer_ids.length;i++){var id=job.offer_ids[i],comp=null;for(var c=0;c<doc.layerComps.length;c++)if(doc.layerComps[c].name==='OFERTA '+id)comp=doc.layerComps[c];if(!comp)throw Error('MISSING_COMP|'+id);comp.apply();doc.layerSets.getByName('#GUIAS').visible=false;var png=new File(folder.fsName+'/byd_'+id+'_'+t.format+'.png');if(png.exists)throw Error('REFUSE_OVERWRITE');var eo=new ExportOptionsSaveForWeb();eo.format=SaveDocumentType.PNG;eo.PNG8=false;eo.transparency=false;eo.includeProfile=true;doc.exportDocument(png,ExportType.SAVEFORWEB,eo);msg('OK|png|'+id+'|'+t.format);}doc.close(SaveOptions.DONOTSAVECHANGES);doc=null;msg('OK|format|'+t.format+'|elapsed_ms='+(new Date().getTime()-t0));}msg('OK|completed|elapsed_ms='+(new Date().getTime()-start));
}catch(e){msg('ERRO|'+e.message+'|line='+e.line);throw e;}finally{if(doc)doc.close(SaveOptions.DONOTSAVECHANGES);app.displayDialogs=old;if(log)log.close();}})();
